### PR TITLE
Reexport now handles optional leading `::` in path

### LINKED ISSUE #36: `#[proc_macro_hack]` reexport cannot handle leading `::` in path
As we can see from [the code](https://github.com/dtolnay/proc-macro-hack/blob/ca8854bc92b2621748b8031d327e7208bcd792e8/src/lib.rs#L189), when using the `#[proc_macro_hack]` attribute to "decorate" a reexport (_i.e._, in the "declaration crate"), it expects to start parsing

```rust
use $implementation_crate_name:ident ::
```

However, given that we are reexporting from a crate, a way to do this in the 2018 edition (the cleanest way imho, since it avoids any potential path ambiguity), would be to use a leading pair of colons:

```rust
#[proc_macro_hack]
use ::implementation_crate_name::proc_macro_name;
```

That's why it would be great if `proc_macro_hack` in reexport position was changed so that it expects to start parsing

```rust
use $(::)? $implementation_crate_name:ident ::
```

### PR DESCRIPTION
**Pull request by danielhenrymantilla**
Fixes https://github.com/dtolnay/proc-macro-hack/issues/36

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by dtolnay** [comment]
Please add your work email to https://github.com/settings/emails if you would like for this commit to be attributed to your account.

**Comment by danielhenrymantilla** [comment]
Done: my address should no longer be private

**Comment by dtolnay** [comment]
I don't think it worked -- notice that https://github.com/dtolnay/proc-macro-hack/commit/4715ce1a80dc7f0965431eb853afc2295611eae2 does not link to https://github.com/danielhenrymantilla. You need an email in https://github.com/settings/emails that matches the one in https://github.com/dtolnay/proc-macro-hack/commit/4715ce1a80dc7f0965431eb853afc2295611eae2.patch.

**Comment by danielhenrymantilla** [comment]
You're right, I had the wrong email in my git config when I commited; well, never mind then, given how small the change is ^^

**Pull request merged**
